version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gcdiff
    main: ./cmd/gcdiff
    binary: gcdiff
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: gcdiff
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

brews:
  - name: gcdiff
    repository:
      owner: tflynn3
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    homepage: https://github.com/tflynn3/gcdiff
    description: "A terminal tool for comparing and auditing GCP resources across projects"
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "gcdiff"
    test: |
      system "#{bin}/gcdiff", "--version"
